apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mo6kfftz5-go 
  janus-idp.io/tekton: mo6kfftz5-go
  backstage.io/kubernetes-id: mo6kfftz5-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mo6kfftz5-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml